#!/bin/bash

pip install brownie 
pip install django
pip install jinja2
pip install mysql-python
pip install PIL
pip install PyYAML
pip install Pygments
pip install South
pip install Sphinx
pip install argh
pip install argparse
pip install coverage
pip install httplib2
pip install distribute
pip install python-ldap
pip install django-auth-ldap
pip install django-coverage
pip install django-debug-toolbar
pip install django-indexer
pip install django-jsonfield
pip install django-modeldict
pip install django-native-tags
pip install django-paging
pip install django-secretballot
pip install django-sentry
pip install django-tagging
pip install django-tastypie
pip install django-templatetag-sugar
pip install django-uuidfield
pip install docutils
pip install eventlet
pip install feedparser
pip install gargoyle
pip install greenlet
pip install gunicorn
pip install hiredis
pip install jsonpickle
pip install jsonfield
pip install lockfile
pip install mimeparse
pip install MySQL-Connector
pip install nexus
pip install nose
pip install pathtools
pip install python-daemon
pip install python-dateutil
pip install python-digest
pip install python-memcached
pip install python-openid
pip install python-twitter
pip install twitter
pip install py4j
pip install beautifulsoup
pip install raven
pip install redis
pip install django-redis-cache
pip install nexus-redis
pip install select-backport
pip install simplejson
pip install uuid
pip install vobject
pip install watchdog
pip install wsgiref
pip install xlrd
pip install yolk
